### ISSUE TITLE
RuntimeError: GET was unable to find an engine to execute this computation

### ISSUE THREAD

**Issue by zhini-web** [lehduong/OneDiffusion#12]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:36<00:00,  1.37it/s]
Traceback (most recent call last):
  File "inference.py", line 11, in <module>
    output = pipeline(
  File "/root/miniconda3/envs/onediffusion_env/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/WujieAITeam/private/yht/OneDiffusion/onediffusion/diffusion/pipelines/onediffusion.py", line 569, in __call__
    image = self.vae.decode(latents.to(self.vae.dtype)).sample
  File "/root/miniconda3/envs/onediffusion_env/lib/python3.8/site-packages/diffusers/utils/accelerate_utils.py", line 46, in wrapper
    return method(self, *args, **kwargs)
  File "/root/miniconda3/envs/onediffusion_env/lib/python3.8/site-packages/diffusers/models/autoencoders/autoencoder_kl.py", line 321, in decode
    decoded = self._decode(z).sample
  File "/root/miniconda3/envs/onediffusion_env/lib/python3.8/site-packages/diffusers/models/autoencoders/autoencoder_kl.py", line 292, in _decode
    dec = self.decoder(z)
  File "/root/miniconda3/envs/onediffusion_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/onediffusion_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/onediffusion_env/lib/python3.8/site-packages/diffusers/models/autoencoders/vae.py", line 291, in forward
    sample = self.conv_in(sample)
  File "/root/miniconda3/envs/onediffusion_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/onediffusion_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/onediffusion_env/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/root/miniconda3/envs/onediffusion_env/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: GET was unable to find an engine to execute this computation

**Comment by zhini-web** [comment]
echo $LD_LIBRARY_PATH 
export OLD_LD_LIBRARY_PATH=$LD_LIBRARY_PATH 
unset LD_LIBRARY_PATH
